#!/bin/bash

# build.sh - Auto-generate command documentation for README.md
# 
# This script uses clap-markdown to generate comprehensive command documentation
# directly from the CLI definition, ensuring the README always stays up-to-date
# with the actual command structure.
#
# How it works:
# 1. Builds the release binary
# 2. Uses the hidden --markdown-help flag to generate markdown documentation
# 3. Replaces the content between <!-- BEGIN AUTO-GENERATED COMMANDS --> 
#    and <!-- END AUTO-GENERATED COMMANDS --> markers in README.md
# 4. Preserves all other content in the README
#
# Usage: ./build.sh
#
# The script is idempotent - safe to run multiple times.

echo "🔧 Building timetracker..."
cargo build --release

if [ $? -ne 0 ]; then
    echo "❌ Build failed. Exiting."
    exit 1
fi

echo "✅ Build successful."

# Generate markdown help using our hidden flag
echo "📝 Generating command documentation..."
MARKDOWN_HELP=$(./target/release/timetracker --markdown-help)

if [ $? -ne 0 ]; then
    echo "❌ Failed to generate markdown help. Exiting."
    exit 1
fi

echo "✅ Command documentation generated."

# File processing: Replace the auto-generated section
README_FILE="README.md"
TEMP_FILE="README_temp.md"

# Extract content before the marker
awk '/<!-- BEGIN AUTO-GENERATED COMMANDS -->/{exit} {print}' "$README_FILE" > "$TEMP_FILE"

# Add the marker and new content
cat >> "$TEMP_FILE" << 'EOF'
<!-- BEGIN AUTO-GENERATED COMMANDS -->
<!-- This section is automatically generated by build.sh -->
<!-- Do not edit manually - changes will be overwritten -->

EOF

# Add the generated markdown help (skip the first 2 lines which contain the title)
echo "$MARKDOWN_HELP" | tail -n +3 >> "$TEMP_FILE"

# Add closing marker
echo "" >> "$TEMP_FILE"
echo "<!-- END AUTO-GENERATED COMMANDS -->" >> "$TEMP_FILE"

# Extract content after the marker
awk '/<!-- END AUTO-GENERATED COMMANDS -->/{found=1; next} found {print}' "$README_FILE" >> "$TEMP_FILE"

# Replace the original file atomically
mv "$TEMP_FILE" "$README_FILE"

echo "✅ README.md updated with latest command documentation."
echo ""
echo "📝 Summary:"
echo "   - Built release binary"
echo "   - Generated command documentation using clap-markdown" 
echo "   - Updated README.md between AUTO-GENERATED COMMANDS markers"
echo ""
echo "🎉 Documentation update complete!"
echo ""
echo "💡 Tip: This script is idempotent - safe to run anytime you update CLI commands." 